# GitHub Actions 워크플로우: React 앱을 GitHub Pages에 자동 배포
name: Deploy to GitHub Pages

# 워크플로우 실행 조건: master 브랜치에 push하거나 PR이 생성될 때
on:
  push:
    branches: [ master ]  # master 브랜치에 push할 때 실행
  pull_request:
    branches: [ master ]  # master 브랜치로 PR 생성할 때 실행

# 실행할 작업들
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행
    
    steps:
    # 1단계: GitHub 저장소 코드를 체크아웃
    - name: Checkout
      uses: actions/checkout@v3
      
    # 2단계: Node.js 환경 설정 (버전 18, npm 캐시 사용)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Node.js 18 버전 사용
        cache: 'npm'        # npm 캐시 사용으로 설치 속도 향상
        
    # 3단계: 의존성 설치 (npm install 대신 npm ci 사용 - 더 빠르고 안정적)
    - name: Install dependencies
      run: npm install  # npm ci 대신 npm install 사용
      
    # 4단계: React 앱 빌드 (production용 최적화된 빌드)
    - name: Build
      run: npm run build
      
    # 5단계: GitHub Pages에 배포 (master 브랜치일 때만)
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # GitHub Pages 배포 액션
      if: github.ref == 'refs/heads/master'  # master 브랜치일 때만 배포
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 토큰 사용
        publish_dir: ./build  # build 폴더의 내용을 배포
